<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Completed Tasks</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <style>
        body {
            margin: 50px 0 0 0;
            padding: 0;
            width: 100%;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            text-align: center;
            color: #aaa;
            font-size: 18px;
            background-color: lightblue;
        }

        h1 {
            color: #719e40;
            letter-spacing: -3px;
            font-family: 'Lato', sans-serif;
            font-size: 100px;
            font-weight: 200;
            margin-bottom: 0;
        }

        h3 {
            margin: 0.4rem;
            color: #fff;
        }

        label {
            font-size: 24pt;
        }

        .form1 {
            display: flex;
            align-items: center;
            justify-content: center;
            margin: 2rem;
        }

        .complete_button {
            /*padding: 0;*/
            background-color: #fff;
            border: 0.1rem solid grey;
            height: 1.4rem;

        }

        .incomplete_tasks_container {
            display: flex;
            flex-direction: column;
            text-align: left;
            padding-left: 39%;
        }

        .incomplete_task {
            display: flex;
            align-items: center;
        }

        .task_box {
            width: 400px;
            height: 30px;
            font-size: 18pt;
            margin: 0.4rem;
            color: grey;
        }

        .add_button {
            height: 36px;
            background-color: #fff;
            border: 0.1rem solid grey;
        }

    </style>
</head>
<body>
<h1>Completed Tasks</h1>
<?php
foreach($completedTasks as $taskItem)
{
    echo '<h3>'.$taskItem['task'].'</h3>';
}
?>
</body>
</html>