<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Completed Tasks</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <style>
        body {
            margin: 50px 0 0 0;
            padding: 0;
            width: 100%;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            text-align: center;
            color: #aaa;
            font-size: 18px;
            background-color: lightblue;
        }

        h1 {
            color: #719e40;
            letter-spacing: -3px;
            font-family: 'Lato', sans-serif;
            font-size: 100px;
            font-weight: 200;
            margin-bottom: 0;
        }

        h3 {
            margin: 0.4rem;
            color: #fff;
        }

        label {
            font-size: 24pt;
        }

        .complete_tasks_container {
            display: flex;
            flex-direction: column;
            text-align: left;
            padding-left: 32.6%;
        }

        .complete_task {
            display: flex;
            align-items: center;
        }

        .delete_btn {
            background-color: #fff;
            font-size: 12pt;
        }

    </style>
</head>
<body>
<h1>Completed Tasks</h1>
<div class="complete_tasks_container">
<?php
foreach($completedTasks as $taskItem)
{
    echo '<div class="complete_task">'
        .'<h3>'.$taskItem['task'].'</h3>'
        .'<form method="POST" action="/deleted">'
        .'<input type="hidden" name="delete" value="'. $taskItem['id'] .'">'
        .'<input class="delete_btn" type="submit" value="delete">'
        .'</form>'
        .'</div>';
}
?>
<a href="/">uncompleted tasks</a>
</div>
</body>
</html>